### ISSUE TITLE
Unable to build because of invalid git repos

### ISSUE THREAD

**Issue by cglukas** [juangea/boneMaster#10]
Hi,

i tried to get my hands on your amazing build, but unfortunately i can't even build it.
I always get the following message:
![Screenshot_3](https://user-images.githubusercontent.com/48561400/107130479-1c2a0680-68ce-11eb-86f7-af5f3971e536.jpg)

I installed all the software to build blender and build it successfully. But your build doesn't want to go.
Maybe you've got a solution for my problem.
Best Regards,
Lukas

**Comment by juangea** [comment]
What branch are you trying to build?

**Comment by juangea** [comment]
Also, are you following the instructions in the wiki?

**Comment by cglukas** [comment]
Hi, no I didn't check the wiki. might try it that way.... Thanks. 
Maybe it would be good to include a wiki link in your readme. I rushed it and didn't found the wiki.
